name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: 'Run Specific Job'
        required: false
        type: boolean

      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ inputs.custom_message }}"
      - name: Printing run-job boolean value
        if: inputs.run-job
        run: echo "${{ inputs.run-job }}"
  
